---
apiVersion: v1
kind: Pod
metadata:
  name: pody
  namespace: monitor
  labels:
    app: pody
spec:
  containers:
  - name: pody
    image: pod:latest
    imagePullPolicy: Never
    ports:
    - containerPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: pody
  labels:
    app: pody
spec:
  selector:
    app: pody
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088
