---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitor
data:
  prometheus.yml: |
    global:
      scrape_interval:     15s 
      evaluation_interval: 15s

    scrape_configs:
      - job_name: node
        static_configs:
        - targets: ['10.73.1.115:32500', 'nodex:9100', 'pody:8088']
